apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    # keep or update the version you want
    targetRevision: 6.6.3
    helm:
      values: |
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          useTestSchema: true

        singleBinary:
          replicas: 1
           persistence:
            enabled: true
            size: 1Gi
            

        # Make sure scalable components are OFF
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false 

        gateway:
          enabled: true

        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
