apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.3
    helm:
      values: |
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          persistence:
            enabled: false
        singleBinary:
          replicas: 1
        gateway:
          enabled: true
        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
