apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.3
    helm:
      values: |
        # Run the lightweight single-binary variant
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          storage:
            type: filesystem
          # Quick start schema (no persistence). Replace with schemaConfig later.
          useTestSchema: true
          # Make root FS writable inside the container
          containerSecurityContext:
            readOnlyRootFilesystem: false
          # Ruler needs a writable dir
          ruler:
            storage:
              type: local
              local:
                directory: /var/loki/rules

        singleBinary:
          replicas: 1
          persistence:
            enabled: false
          # Give Loki a writable /var/loki via emptyDir
          extraVolumes:
            - name: loki-data
              emptyDir: {}
          extraVolumeMounts:
            - name: loki-data
              mountPath: /var/loki

        # Turn OFF scalable components and chunk cache (saves resources)
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false

        # Enable gateway and promtail shipping logs to Loki
        gateway:
          enabled: true

        promtail:
          enabled: true
          config:
            clients:
              - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
