apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.16.2
    helm:
      values: |
        tempo:
          retention: 24h
          storage:
            trace:
              backend: local
              wal: { path: /var/tempo/wal }
              local: { path: /var/tempo/blocks }
          receivers:
            otlp:
              protocols:
                http: { endpoint: 0.0.0.0:4318 }
                grpc: { endpoint: 0.0.0.0:4317 }
          server:
            http_listen_port: 3200
        persistence:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
